# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               code X jitsu
tagline:             'A developers blog'
description:         'A Chicago based web developer and Brazilian Jujitsu addict'
url:                 'http://berimbolo.github.io'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alejandro Ruiz
  url:               https://twitter.com/alexruiz1871
  email:             alejandroruiz1871@gmail.com

# Custom vars
version:             1.0.0
